name: BiliSummary
options:
  bundleIdPrefix: com.jakevin
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "FABM2QUA8Q"
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGNING_REQUIRED: "YES"
    CODE_SIGNING_ALLOWED: "YES"
    CODE_SIGN_STYLE: "Automatic"
    SWIFT_ENABLE_EXPLICIT_MODULES: "NO"
    USE_HEADERMAP: "NO"

targets:
  BiliSummary:
    type: application
    platform: iOS
    sources:
      - path: BiliSummary
    settings:
      base:
        INFOPLIST_FILE: BiliSummary/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jakevin.BiliSummary
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
